name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Build
        run: |
          yarn install
          yarn build

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Prettier
        run: |
          yarn prettier --check ./src/
